#!/usr/bin/env python3

import json
from redbaron import RedBaron
import sys

def catchdump(x):
  try:    
    return x.dumps()      
  except:
    pass  

def hasMultiStmt(node):
  l =[]
  for nd in node:
    nodes = nd.find_all(['ifelseblock','atomtrailers', 'return'], recursive=False)
    nodes = nodes.filter(lambda x: x != None)
    l.extend(nodes)
  return len(l) > 1

def getScratch(red):
    s = red.find_all('assign')
    if isinstance(s, list):
      s = s.filter(lambda x: 'ScratchVar' in x)
    if s:
      return '\n'.join(s.map(lambda x: x.dumps()))
    else:
      return ''

def findmap(red, which, how):
    l = red.find_all(which)
    l.map(how)

def all(red):
  try: 
    findmap(red, 'boolean_operator', bools)
    findmap(red, 'int', ints)
    findmap(red, 'ifelseblock', ifs)    
    strs_ = []
    hasMulti = hasMultiStmt(red)
    scratch = getScratch(red)
    for nd in red:
      nodes = nd.find_all(['ifelseblock','atomtrailers', 'return'], recursive=False)
      if hasMulti:
        findmap(nodes, 'return', returns)
        
      strs = nodes.map(catchdump)
      strs = strs.filter(lambda x: x != None)
      strs_.extend(strs)
    if len(strs_) > 1:
      strlist = ',\n'.join(strs_)
      red.value = f"{scratch}\nreturn Seq([{strlist}])\n"    
  except BaseException as err:
    print(f"Unexpected {err=}, {type(err)=}")  
    pass

def bools(boolOp):
  all(boolOp.first)
  all(boolOp.second)
  boolOp.parent.value = f"{boolOp.value.title()}({boolOp.first}, {boolOp.second})"

def ifs(if_):
  all(if_.value)
  if_.value = f"If({if_.value[0].test.dumps()}, {if_.value[0].value.dumps()})\n\n"

def returns(ret):
  all(ret.value)
  ret.replace(f"Return({ret.value.dumps().replace('return ','')})")

def ints(i):
  try:
    if i.parent.parent.parent.value[0].value == 'Int':
      return
  except:
    pass
  i.replace(f"Int({i.value})")

def convert(fname):
  source = open(fname, "r")
  red = RedBaron(source.read())
  findmap(red, 'def', all)  
  print("from pyteal import *\n")
  print("globals().update(TealType.__members__)")
  print(red.dumps())
  print('if __name__ == "__main__":\n    print(compileTeal(teal(), mode=Mode.Application, version=5))')

convert(sys.argv[1])

