#!/bin/bash
EXAMPLES="examples/*"
for ex in $EXAMPLES
do
  echo -n "$ex.."  
  if ! ./genteal >/dev/null $ex 2>&1; then
    echo -e "\e[91m✗\e[39m"
  else
    echo -e "\e[92m✓\e[39m"
  fi
done
cd ..
  
